before_build:
- nuget restore Color.Comment.sln

version: '{build}'

-
  branches:
    only:
      - 2017

  image:
  - Visual Studio 2017

-
  branches:
    only:
      - master
  
  image:
  - Visual Studio 2019 Preview